trigger:
  branches:
    include:
      - main

pool: ubuntu-latest

stages:
  - stage: build
    jobs:
      - job: buildcode
        displayName: BuildMytodoapp
        steps:
        - task: PowerShell@2
          inputs:
            filePath: 'npm run build'

            